import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import PageShell from '../components/PageShell'; import { eventAPI, aiAPI, clubAPI } from '../services/api'; import { socket } from '../services/socket';
const empty={title:'',description:'',category:'Hackathon',date:'',time:'',location:'',capacity:100,clubId:''};
export default function Dashboard(){
 const location=useLocation(); const navigate=useNavigate();
 const[events,setEvents]=useState([]);const[clubs,setClubs]=useState([]);const[form,setForm]=useState(empty);const[saving,setSaving]=useState(false);const[deletingId,setDeletingId]=useState(null);const[editingId,setEditingId]=useState(null);const[showForm,setShowForm]=useState(false);const[registrations,setRegistrations]=useState(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[error,setError]=useState('');const[insight,setInsight]=useState('');const[insightLoading,setInsightLoading]=useState(false);
 const load=()=>eventAPI.getMyEvents().then(r=>setEvents(Array.isArray(r.data)?r.data:[])).catch(e=>setError(e.message)).finally(()=>setLoading(false));
 const loadInsight=async()=>{setInsightLoading(true);try{const r=await aiAPI.insights();setInsight(r.data.insight)}catch(e){setInsight(e.message)}finally{setInsightLoading(false)}};
 useEffect(()=>{ load(); clubAPI.getMine().then(r=>setClubs(r.data||[])).catch(()=>{}); loadInsight(); const onReg=({eventId,registrationCount})=>setEvents(prev=>prev.map(e=>e._id===eventId?{...e,registrationCount}:e)); socket.on('registration:updated',onReg); return()=>socket.off('registration:updated',onReg); },[]);
 useEffect(()=>{ if(location.pathname==='/organizer/create-event'){ setEditingId(null); setForm({...empty}); setShowForm(true); setMessage(''); setError(''); } },[location.pathname]);
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 function openCreate(){setEditingId(null);setForm({...empty});setShowForm(true);setMessage('');setError(''); if(location.pathname!=='/organizer/create-event') navigate('/organizer/create-event')}
 function openEdit(e){setEditingId(e._id);setForm({title:e.title,description:e.description,category:e.category,date:new Date(e.date).toISOString().slice(0,10),time:e.time,location:e.location,capacity:e.capacity,clubId:e.club?._id||''});setShowForm(true);setMessage('');setError('')}
 async function save(e){e.preventDefault();setError('');setMessage('');setSaving(true);try{if(editingId)await eventAPI.updateEvent(editingId,{...form,capacity:Number(form.capacity)});else await eventAPI.createEvent({...form,capacity:Number(form.capacity)});setMessage(editingId?'Event updated and sent for approval.':'Event submitted for admin approval.');setForm(empty);setEditingId(null);setShowForm(false);navigate('/organizer/dashboard',{replace:true});load()}catch(x){setError(x.message)}finally{setSaving(false)}}
 async function remove(id){if(!window.confirm('Delete this event?'))return;setDeletingId(id);try{await eventAPI.deleteEvent(id);if(registrations) setRegistrations(null);load()}catch(x){setError(x.message)}finally{setDeletingId(null)}}
 async function viewRegistrations(id){setError('');try{const r=await eventAPI.getRegistrations(id);setRegistrations({id,data:r.data})}catch(x){setError(x.message)}}
 return <PageShell><section className="container-page py-12"><p className="text-sm font-bold text-primary">Organizer workspace</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="mt-2 text-4xl font-black">Dashboard</h1><p className="mt-2 text-gray-500">Manage your real CampusPulse events.</p></div><button onClick={openCreate} className="rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white">Create Event</button></div>{message&&<p className="mt-5 rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-700">{message}</p>}{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
 {showForm&&<form onSubmit={save} className="mt-8 rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-black">{editingId?'Edit event':'Create event'}</h2><button type="button" onClick={()=>{setShowForm(false); if(location.pathname==='/organizer/create-event') navigate('/organizer/dashboard')}} className="text-sm font-bold text-gray-500">Close</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Field name="title" label="Title" value={form.title} update={update}/><Field name="category" label="Category" value={form.category} update={update}/><Field name="date" label="Date" type="date" value={form.date} update={update}/><Field name="time" label="Time" value={form.time} update={update}/><Field name="location" label="Location" value={form.location} update={update}/><Field name="capacity" label="Capacity" type="number" value={form.capacity} update={update}/><label className="text-sm font-semibold">Club (optional)<select name="clubId" value={form.clubId||""} onChange={update} className="mt-1 w-full rounded-xl border bg-white p-3"><option value="">No club</option>{clubs.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="text-sm font-semibold md:col-span-2">Description<textarea name="description" required value={form.description} onChange={update} rows="4" className="mt-1 w-full rounded-xl border p-3"/></label></div><button disabled={saving} className="mt-5 rounded-xl bg-gray-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving?'Saving...':editingId?'Save Changes':'Submit for Approval'}</button></form>}
 <div className="mt-8 rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-primary">AI Organizer Insights</p><h2 className="mt-1 text-xl font-black">Data-backed event insights</h2></div><button onClick={loadInsight} disabled={insightLoading} className="rounded-lg border px-3 py-2 text-xs font-bold">{insightLoading?'Analyzing...':'Refresh'}</button></div>{insight&&<p className="mt-4 whitespace-pre-line text-sm leading-6 text-gray-700">{insight}</p>}</div>
 <div className="mt-8 grid grid-cols-2 gap-4 lg:grid-cols-4">{[[events.length,'Events'],[events.reduce((a,e)=>a+(e.registrationCount||0),0),'Registrations'],['—','Attendance'],['—','Rating']].map(x=><div className="rounded-2xl border bg-white p-5" key={x[1]}><p className="text-2xl font-black">{x[0]}</p><p className="mt-1 text-sm text-gray-500">{x[1]}</p></div>)}</div>
 <div className="mt-8 rounded-2xl border bg-white p-6"><h2 className="font-black">Your events</h2>{loading?<p className="mt-4 text-sm text-gray-500">Loading...</p>:!events.length?<p className="mt-4 text-sm text-gray-500">You have not created an event yet.</p>:events.map(e=><div key={e._id} className="flex flex-col gap-3 border-b py-4 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"><div><b>📅 {e.title}</b><p className="text-xs text-gray-500">{new Date(e.date).toLocaleDateString()} · {e.registrationCount||0} registered · <span className="font-bold">{e.status}</span></p></div><div className="flex flex-wrap gap-2"><button onClick={()=>openEdit(e)} className="rounded-lg border px-3 py-2 text-xs font-bold">Edit</button><button onClick={()=>viewRegistrations(e._id)} className="rounded-lg border px-3 py-2 text-xs font-bold">Registrations</button><button disabled={deletingId===e._id} onClick={()=>remove(e._id)} className="rounded-lg border px-3 py-2 text-xs font-bold text-red-600 disabled:opacity-60">{deletingId===e._id?'Deleting...':'Delete'}</button></div></div>)}</div>
 {registrations&&<div className="mt-8 rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-black">Registrations ({registrations.data.length})</h2><button onClick={()=>setRegistrations(null)} className="text-sm font-bold text-gray-500">Close</button></div>{!registrations.data.length?<p className="mt-4 text-sm text-gray-500">No registrations yet.</p>:<div className="mt-4 grid gap-2">{registrations.data.map(r=><div key={r._id} className="rounded-xl bg-gray-50 p-3 text-sm"><b>{r.user?.name}</b><span className="ml-2 text-gray-500">{r.user?.email}</span></div>)}</div>}</div>}
 </section></PageShell>
}
function Field({name,label,type='text',value,update}){return <label className="text-sm font-semibold">{label}<input name={name} type={type} required value={value} onChange={update} className="mt-1 w-full rounded-xl border p-3"/></label>}
